### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by kerrambit** [kerrambit/CommandParsonaut#19]
**Prepare release of 2.0.0**

- [x] https://github.com/kerrambit/CommandParsonaut/issues/18
- [x] Clean code
- [x] Readme
- [x] Project properties updated
- [x] Resolve merge conflicts
- [x] Update NuGet
- [ ] Release

**Comment by kerrambit** [comment]
#18 will be done in next release...
